MODULE_big = vptree
OBJS = vptree.o

EXTENSION = vptree
DATA = vptree--1.0.sql

subdir = ../vptree
top_builddir = ../postgresql
include $(top_builddir)/src/Makefile.global
include $(top_srcdir)/contrib/contrib-global.mk

vptree.o: vptree.c

